---
title: "De kunst van statistiek"
description: |
  Hoe helpt statistiek ons om de wereld te begrijpen? Kunnen we betrouwbare conclusies trekken als onze data niet perfect zijn? Hoe verandert statistiek in de tijd van datawetenschap? Dit zijn de drie vragen die David Spiegelhalter centraal stelt in zijn "The art of statistics" dat hij ondertussen alweer twee jaar geleden schreef. Dit boek helpt ons om de grote lijn vast te houden waar detailzaken ons zo vaak helemaal in beslagnemen.  
author:
  - name: Harrie Jonkman
    url: https://easystats.github.io/bayestestR/
#date: 01-17-2021
#output:
  #distill::distill_article:
   # self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In 2020 las ik verschillende boeken waar ik als onderzoeker veel van heb geleerd. Allereerst is daar de herziene versie van Richard McElreaths [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/), waar ik eerder enthousiast over heb geschreven [titel](). Dan is er het R boek over onderwijsonderzoek [Data science in education using R](https://datascienceineducation.com/) van Estrellado en anderen dat mij interesseerde. In de zomer vroeg ik mij af wanneer komt Andrew Gelmal weer eens met een nieuw boek. Toen ik daar naar zocht, zag ik dat zijn [Regression and other stories](https://statmodeling.stat.columbia.edu/2020/07/08/regression-and-other-stories-is-available/) net was uitgekomen dat hij schreef met Jennifer Hill en Aki Vehtari. Een waardige 
opvolger van xx. Een vierde boek dat mij interesseerde en verscheen in 2020 gaat over machine learning, waar ik graag iets meer over zou willen leren. Hier verscheen het boek van Max Kun en Julia Silge [Tidymodelling using R](https://juliasilge.com/blog/tidymodels-book/) dat mij interesseerde en waar ik dit jaar beter naar wil kijken. Het boek dat ik in 2020 las en mij veruit de meeste indruk op mij maakte was het boek van David Spiegelhalter [The Art of Statistics. Learning from Data](https://www.penguin.co.uk/books/294/294857/learning-from-data/9780241258767.html). Het boek verscheen al een jaar eerder maar het kwam in 2020 in pocketvorm uit. Een prachtig boek dat je steeds opnieuw erbij pakt.

David Spiegelhalter is een fenomeen. Hij is bekend geworden als statisticus die de Bayesiaanse statistiek toepasbaar en breder bruikbaar maakte. Hij leidde het onderzoeksteam dat WinBUGS ontwikkelde waarmee, met enige training, data Bayesiaans geanalyseerd kunnen worden. De laatste tien jaar is hij vooral als communicator bekend in eigen land als ...
David Spiegelhalter is zich ervan bewust dat in deze tijd worden overstelpt met data. Hoe we hiermee omgaan is niet alleen een technisch vraagstuk maar misschien nog wel meer een conceptueel vraagstuk. 
Thema's

Inhoud

Baysiaans

Trust

Covid en wat we hiervan leren






